### ISSUE TITLE
OpenGLSC2 headers are not generated by make

### ISSUE THREAD

**Issue by DeepakRavikumarIMG** [KhronosGroup/OpenGL-Refpages#119]
xml/Makefile misses out listing OpenGL SC2 header files and hence it's not getting generated.

**Comment by pdaniell-nv** [comment]
Should this issue be under https://github.com/KhronosGroup/OpenGL-Registry?

**Comment by oddhack** [comment]
Closing in favor of https://github.com/KhronosGroup/OpenGL-Registry/pull/514
