### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AntonioNoack** [KhronosGroup/OpenGL-Refpages#120]
Hey, I found a typo in the Khronos docs, but was unsure where I can report that. So I report it here, in hope sb finds it, who knows how to properly report it.

Document: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/imageAtomicMax.xhtml
Typo: "imageAtomic**Max** — atomically compute the **min**imum of a value [...]" should be "imageAtomicMax — atomically compute the **max**imum of a value [...]"

**Comment by oddhack** [comment]
Thanks! Occurred in the ES page as well, too much cut & paste. Should be fixed now.
