### ISSUE TITLE
Error: width as with in `glFramebufferParameteri.xhtml`

### ISSUE THREAD

**Issue by shutaozhenzhen** [KhronosGroup/OpenGL-Refpages#155]
https://github.com/KhronosGroup/OpenGL-Refpages/blob/f50027c1c911e019648a6a08176aa6813de66d47/es3.1/html/glFramebufferParameteri.xhtml#L116

specifies the assumed ***with*** for a framebuffer object with no attachments.

specifies the assumed ***width*** for a framebuffer object with no attachments.

**Comment by oddhack** [comment]
Thanks! This should be fixed now. It may take a little while to propagate to registry.khronos.org from github.
