### ISSUE TITLE
textureGrad / textureGradOffset errors

### ISSUE THREAD

**Issue by imirkin** [KhronosGroup/OpenGL-Refpages#27]
textureGrad:
 - gsampler2DRectShadow takes a vec3
 - sampler1DShadow takes a vec2
 - missing 2DArrayShadow
 - missing CubeShadow

textureGradOffset:
 - sampler1DShadow takes a vec2
 - sampler2DArrayShadow takes a vec4

**Comment by oddhack** [comment]
@imirkin any chance you could post a pull request for the affected ref page Docbook sources? I assume they would be Refpages/{gl4,es3}/textureGrad{,Offset}.xml . And the es3.1 / es3.0 versions if the fixes are applicable to the corresponding versions of ESSL.

**Comment by imirkin** [comment]
That was my original plan, but I got confused with the markup details. I
tried to build the HTML, but I got a ton of diffs for the existing stuff,
so decided to leave it to the professionals.

Some of the changes should be straightforward, but I think it makes sense
to fix these all at once.
