### ISSUE TITLE
es3 and gl4 glGenVertexArrays man page has weird output and odd indentation

### ISSUE THREAD

**Issue by wirecat** [KhronosGroup/OpenGL-Refpages#34]
Looks like the man page generation for glGenVertexArrays has something goofy going on. Attached is the output.

I believe this is only affecting es3, gl4 and any version where the xml docs are using xml namespaces.

Tested using:
OS: Arch Linux (up to date)
Package: opengl-man-pages
Package Version: 20170404-1

If someone pointed me in the right direction I would work on this. I've been looking into it already, but am having a hard time getting started.

[glGenVertexArrays_ManOutput.txt](https://github.com/KhronosGroup/OpenGL-Refpages/files/1756771/glGenVertexArrays_ManOutput.txt)

e: Clarified that this is only for man pages on arch using a specific package.
e2: Clarified which version are effected.

**Comment by wirecat** [comment]
I think I have a fix in mind and will be trying it out this week. It all has to do with whitespace getting generated in the gl4 generation. For some reason, xsltproc really doesn't like the xmlns that the gl4 docs have. This affects more than just glGenVertexArrays, but it was only visible there to me because the arch package is compiled in a weird way.

**Comment by ahuillet** [comment]
I see the same problem on Arch with a various GL functions - GenVertexArrays, MultiDrawElementsIndirect, and others. @wirecat, any thoughts for a possible fix?
