### ISSUE TITLE
GLES 3 glDepthRangef clamping behaviour

### ISSUE THREAD

**Issue by joonazan** [KhronosGroup/OpenGL-Refpages#46]
The spec is very unclear on where the clamping happens for depth values. We asked Mark Kilgard, and his interpretation was that clamping should occur immediately, like in GLES 2.

The reference pages state that clamping should only happen when drawing into a fixed-point depth buffer.

NVIDIA implements immediate clamping and ANGLE does not. In desktop GL the issue is more clear. 4.2 did not clamp, but 4.3 does and requires use of extension functions for specifying a range outside [0, 1].

**Comment by joonazan** [comment]
I am requesting a change to the refpages.

In the GLES 3.x pages "If a fixed-point depth representation is used, the parameters n and f are clamped to the range [0 to 1] when computing window z." should instead say that the arguments are clamped immediately.

I'm just doubting this interpretation of the spec as it makes the function a lot less useful.

**Comment by pdaniell-nv** [comment]
Assigned to @oddhack to make the refpage change. I believe the spec is correct in that the values are clamped when the function is called.
