### ISSUE TITLE
Wrong description of isnan

### ISSUE THREAD

**Issue by BrokenMatrix** [KhronosGroup/OpenGL-Refpages#66]
The page for isnan states

> For each element i of the result, isinf returns true if x[i] is posititve or negative floating point NaN (Not a Number) and false otherwise.

The problem is where it refers to the function as "isinf" when it should be referring to the "isnan" function.

Located at line 46 of [This File](https://github.com/KhronosGroup/OpenGL-Refpages/blob/master/gl4/isnan.xml)

**Comment by oddhack** [comment]
Thanks!
