### ISSUE TITLE
textureLod() taking vec4 for sampler2DShadow in ref page vec3 in spec

### ISSUE THREAD

**Issue by Sknowman** [KhronosGroup/OpenGL-Refpages#73]
The opengl ref pages [https://www.khronos.org/registry/OpenGL-Refpages/gl4/](url) say

float textureLod(sampler2DShadow sampler, **_vec4 P_**, float lod);

The spec [https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf](url)  pg180

float textureLod(sampler2DShadow sampler, **_vec3 P_**, float lod)

vec4 use does not compile

**Comment by oddhack** [comment]
@sknowman please confirm if #74 fixes this issue. Thanks!
