### ISSUE TITLE
Grammar mistake on documentation

### ISSUE THREAD

**Issue by Makogan** [KhronosGroup/OpenGL-Refpages#77]
Hello,

There's a minor mistake on the documentation:
https://github.com/KhronosGroup/OpenGL-Refpages/blob/master/gl4/gl_FragCoord.xml#L54

"It has no affect on rasterization" should be " It has no effect on rasterization".

I know this is super minor but it should be also super simple to fix :)

Thank you for your attention.

**Comment by oddhack** [comment]
Thanks! Fixed in git, registry will update shortly.

**Comment by Makogan** [comment]
Thank you :)
