### ISSUE TITLE
Typo on glMinSampleShading page

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenGL-Refpages#91]
Line 2 on this page:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glMinSampleShading.xhtml

`glMinSampleShading — specifies minimum rate at which sample shaing takes place`

should be 

`glMinSampleShading — specifies minimum rate at which sample shading takes place`

**Comment by oddhack** [comment]
Thanks! Fixed in git, registry should update shortly.
